
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Clubs` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Clubs
 * 
 */
export type ClubsModel = runtime.Types.Result.DefaultSelection<Prisma.$ClubsPayload>

export type AggregateClubs = {
  _count: ClubsCountAggregateOutputType | null
  _avg: ClubsAvgAggregateOutputType | null
  _sum: ClubsSumAggregateOutputType | null
  _min: ClubsMinAggregateOutputType | null
  _max: ClubsMaxAggregateOutputType | null
}

export type ClubsAvgAggregateOutputType = {
  founded_year: number | null
  id: number | null
}

export type ClubsSumAggregateOutputType = {
  founded_year: number | null
  id: number | null
}

export type ClubsMinAggregateOutputType = {
  name: string | null
  city: string | null
  country: string | null
  league: string | null
  founded_year: number | null
  deleted_at: Date | null
  id: number | null
}

export type ClubsMaxAggregateOutputType = {
  name: string | null
  city: string | null
  country: string | null
  league: string | null
  founded_year: number | null
  deleted_at: Date | null
  id: number | null
}

export type ClubsCountAggregateOutputType = {
  name: number
  city: number
  country: number
  league: number
  founded_year: number
  colors: number
  deleted_at: number
  id: number
  _all: number
}


export type ClubsAvgAggregateInputType = {
  founded_year?: true
  id?: true
}

export type ClubsSumAggregateInputType = {
  founded_year?: true
  id?: true
}

export type ClubsMinAggregateInputType = {
  name?: true
  city?: true
  country?: true
  league?: true
  founded_year?: true
  deleted_at?: true
  id?: true
}

export type ClubsMaxAggregateInputType = {
  name?: true
  city?: true
  country?: true
  league?: true
  founded_year?: true
  deleted_at?: true
  id?: true
}

export type ClubsCountAggregateInputType = {
  name?: true
  city?: true
  country?: true
  league?: true
  founded_year?: true
  colors?: true
  deleted_at?: true
  id?: true
  _all?: true
}

export type ClubsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Clubs to aggregate.
   */
  where?: Prisma.ClubsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clubs to fetch.
   */
  orderBy?: Prisma.ClubsOrderByWithRelationInput | Prisma.ClubsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClubsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Clubs
  **/
  _count?: true | ClubsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ClubsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ClubsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClubsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClubsMaxAggregateInputType
}

export type GetClubsAggregateType<T extends ClubsAggregateArgs> = {
      [P in keyof T & keyof AggregateClubs]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClubs[P]>
    : Prisma.GetScalarType<T[P], AggregateClubs[P]>
}




export type ClubsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClubsWhereInput
  orderBy?: Prisma.ClubsOrderByWithAggregationInput | Prisma.ClubsOrderByWithAggregationInput[]
  by: Prisma.ClubsScalarFieldEnum[] | Prisma.ClubsScalarFieldEnum
  having?: Prisma.ClubsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClubsCountAggregateInputType | true
  _avg?: ClubsAvgAggregateInputType
  _sum?: ClubsSumAggregateInputType
  _min?: ClubsMinAggregateInputType
  _max?: ClubsMaxAggregateInputType
}

export type ClubsGroupByOutputType = {
  name: string
  city: string
  country: string
  league: string
  founded_year: number
  colors: string[]
  deleted_at: Date | null
  id: number
  _count: ClubsCountAggregateOutputType | null
  _avg: ClubsAvgAggregateOutputType | null
  _sum: ClubsSumAggregateOutputType | null
  _min: ClubsMinAggregateOutputType | null
  _max: ClubsMaxAggregateOutputType | null
}

export type GetClubsGroupByPayload<T extends ClubsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClubsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClubsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClubsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClubsGroupByOutputType[P]>
      }
    >
  >



export type ClubsWhereInput = {
  AND?: Prisma.ClubsWhereInput | Prisma.ClubsWhereInput[]
  OR?: Prisma.ClubsWhereInput[]
  NOT?: Prisma.ClubsWhereInput | Prisma.ClubsWhereInput[]
  name?: Prisma.StringFilter<"Clubs"> | string
  city?: Prisma.StringFilter<"Clubs"> | string
  country?: Prisma.StringFilter<"Clubs"> | string
  league?: Prisma.StringFilter<"Clubs"> | string
  founded_year?: Prisma.IntFilter<"Clubs"> | number
  colors?: Prisma.StringNullableListFilter<"Clubs">
  deleted_at?: Prisma.DateTimeNullableFilter<"Clubs"> | Date | string | null
  id?: Prisma.IntFilter<"Clubs"> | number
  Players?: Prisma.PlayersListRelationFilter
}

export type ClubsOrderByWithRelationInput = {
  name?: Prisma.SortOrder
  city?: Prisma.SortOrder
  country?: Prisma.SortOrder
  league?: Prisma.SortOrder
  founded_year?: Prisma.SortOrder
  colors?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  id?: Prisma.SortOrder
  Players?: Prisma.PlayersOrderByRelationAggregateInput
}

export type ClubsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ClubsWhereInput | Prisma.ClubsWhereInput[]
  OR?: Prisma.ClubsWhereInput[]
  NOT?: Prisma.ClubsWhereInput | Prisma.ClubsWhereInput[]
  name?: Prisma.StringFilter<"Clubs"> | string
  city?: Prisma.StringFilter<"Clubs"> | string
  country?: Prisma.StringFilter<"Clubs"> | string
  league?: Prisma.StringFilter<"Clubs"> | string
  founded_year?: Prisma.IntFilter<"Clubs"> | number
  colors?: Prisma.StringNullableListFilter<"Clubs">
  deleted_at?: Prisma.DateTimeNullableFilter<"Clubs"> | Date | string | null
  Players?: Prisma.PlayersListRelationFilter
}, "id">

export type ClubsOrderByWithAggregationInput = {
  name?: Prisma.SortOrder
  city?: Prisma.SortOrder
  country?: Prisma.SortOrder
  league?: Prisma.SortOrder
  founded_year?: Prisma.SortOrder
  colors?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  id?: Prisma.SortOrder
  _count?: Prisma.ClubsCountOrderByAggregateInput
  _avg?: Prisma.ClubsAvgOrderByAggregateInput
  _max?: Prisma.ClubsMaxOrderByAggregateInput
  _min?: Prisma.ClubsMinOrderByAggregateInput
  _sum?: Prisma.ClubsSumOrderByAggregateInput
}

export type ClubsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClubsScalarWhereWithAggregatesInput | Prisma.ClubsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClubsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClubsScalarWhereWithAggregatesInput | Prisma.ClubsScalarWhereWithAggregatesInput[]
  name?: Prisma.StringWithAggregatesFilter<"Clubs"> | string
  city?: Prisma.StringWithAggregatesFilter<"Clubs"> | string
  country?: Prisma.StringWithAggregatesFilter<"Clubs"> | string
  league?: Prisma.StringWithAggregatesFilter<"Clubs"> | string
  founded_year?: Prisma.IntWithAggregatesFilter<"Clubs"> | number
  colors?: Prisma.StringNullableListFilter<"Clubs">
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"Clubs"> | Date | string | null
  id?: Prisma.IntWithAggregatesFilter<"Clubs"> | number
}

export type ClubsCreateInput = {
  name: string
  city: string
  country: string
  league: string
  founded_year: number
  colors?: Prisma.ClubsCreatecolorsInput | string[]
  deleted_at?: Date | string | null
  Players?: Prisma.PlayersCreateNestedManyWithoutClubsInput
}

export type ClubsUncheckedCreateInput = {
  name: string
  city: string
  country: string
  league: string
  founded_year: number
  colors?: Prisma.ClubsCreatecolorsInput | string[]
  deleted_at?: Date | string | null
  id?: number
  Players?: Prisma.PlayersUncheckedCreateNestedManyWithoutClubsInput
}

export type ClubsUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  league?: Prisma.StringFieldUpdateOperationsInput | string
  founded_year?: Prisma.IntFieldUpdateOperationsInput | number
  colors?: Prisma.ClubsUpdatecolorsInput | string[]
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  Players?: Prisma.PlayersUpdateManyWithoutClubsNestedInput
}

export type ClubsUncheckedUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  league?: Prisma.StringFieldUpdateOperationsInput | string
  founded_year?: Prisma.IntFieldUpdateOperationsInput | number
  colors?: Prisma.ClubsUpdatecolorsInput | string[]
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.IntFieldUpdateOperationsInput | number
  Players?: Prisma.PlayersUncheckedUpdateManyWithoutClubsNestedInput
}

export type ClubsCreateManyInput = {
  name: string
  city: string
  country: string
  league: string
  founded_year: number
  colors?: Prisma.ClubsCreatecolorsInput | string[]
  deleted_at?: Date | string | null
  id?: number
}

export type ClubsUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  league?: Prisma.StringFieldUpdateOperationsInput | string
  founded_year?: Prisma.IntFieldUpdateOperationsInput | number
  colors?: Prisma.ClubsUpdatecolorsInput | string[]
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ClubsUncheckedUpdateManyInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  league?: Prisma.StringFieldUpdateOperationsInput | string
  founded_year?: Prisma.IntFieldUpdateOperationsInput | number
  colors?: Prisma.ClubsUpdatecolorsInput | string[]
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type ClubsCountOrderByAggregateInput = {
  name?: Prisma.SortOrder
  city?: Prisma.SortOrder
  country?: Prisma.SortOrder
  league?: Prisma.SortOrder
  founded_year?: Prisma.SortOrder
  colors?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
  id?: Prisma.SortOrder
}

export type ClubsAvgOrderByAggregateInput = {
  founded_year?: Prisma.SortOrder
  id?: Prisma.SortOrder
}

export type ClubsMaxOrderByAggregateInput = {
  name?: Prisma.SortOrder
  city?: Prisma.SortOrder
  country?: Prisma.SortOrder
  league?: Prisma.SortOrder
  founded_year?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
  id?: Prisma.SortOrder
}

export type ClubsMinOrderByAggregateInput = {
  name?: Prisma.SortOrder
  city?: Prisma.SortOrder
  country?: Prisma.SortOrder
  league?: Prisma.SortOrder
  founded_year?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
  id?: Prisma.SortOrder
}

export type ClubsSumOrderByAggregateInput = {
  founded_year?: Prisma.SortOrder
  id?: Prisma.SortOrder
}

export type ClubsScalarRelationFilter = {
  is?: Prisma.ClubsWhereInput
  isNot?: Prisma.ClubsWhereInput
}

export type ClubsCreatecolorsInput = {
  set: string[]
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type ClubsUpdatecolorsInput = {
  set?: string[]
  push?: string | string[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type ClubsCreateNestedOneWithoutPlayersInput = {
  create?: Prisma.XOR<Prisma.ClubsCreateWithoutPlayersInput, Prisma.ClubsUncheckedCreateWithoutPlayersInput>
  connectOrCreate?: Prisma.ClubsCreateOrConnectWithoutPlayersInput
  connect?: Prisma.ClubsWhereUniqueInput
}

export type ClubsUpdateOneRequiredWithoutPlayersNestedInput = {
  create?: Prisma.XOR<Prisma.ClubsCreateWithoutPlayersInput, Prisma.ClubsUncheckedCreateWithoutPlayersInput>
  connectOrCreate?: Prisma.ClubsCreateOrConnectWithoutPlayersInput
  upsert?: Prisma.ClubsUpsertWithoutPlayersInput
  connect?: Prisma.ClubsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClubsUpdateToOneWithWhereWithoutPlayersInput, Prisma.ClubsUpdateWithoutPlayersInput>, Prisma.ClubsUncheckedUpdateWithoutPlayersInput>
}

export type ClubsCreateWithoutPlayersInput = {
  name: string
  city: string
  country: string
  league: string
  founded_year: number
  colors?: Prisma.ClubsCreatecolorsInput | string[]
  deleted_at?: Date | string | null
}

export type ClubsUncheckedCreateWithoutPlayersInput = {
  name: string
  city: string
  country: string
  league: string
  founded_year: number
  colors?: Prisma.ClubsCreatecolorsInput | string[]
  deleted_at?: Date | string | null
  id?: number
}

export type ClubsCreateOrConnectWithoutPlayersInput = {
  where: Prisma.ClubsWhereUniqueInput
  create: Prisma.XOR<Prisma.ClubsCreateWithoutPlayersInput, Prisma.ClubsUncheckedCreateWithoutPlayersInput>
}

export type ClubsUpsertWithoutPlayersInput = {
  update: Prisma.XOR<Prisma.ClubsUpdateWithoutPlayersInput, Prisma.ClubsUncheckedUpdateWithoutPlayersInput>
  create: Prisma.XOR<Prisma.ClubsCreateWithoutPlayersInput, Prisma.ClubsUncheckedCreateWithoutPlayersInput>
  where?: Prisma.ClubsWhereInput
}

export type ClubsUpdateToOneWithWhereWithoutPlayersInput = {
  where?: Prisma.ClubsWhereInput
  data: Prisma.XOR<Prisma.ClubsUpdateWithoutPlayersInput, Prisma.ClubsUncheckedUpdateWithoutPlayersInput>
}

export type ClubsUpdateWithoutPlayersInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  league?: Prisma.StringFieldUpdateOperationsInput | string
  founded_year?: Prisma.IntFieldUpdateOperationsInput | number
  colors?: Prisma.ClubsUpdatecolorsInput | string[]
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ClubsUncheckedUpdateWithoutPlayersInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  country?: Prisma.StringFieldUpdateOperationsInput | string
  league?: Prisma.StringFieldUpdateOperationsInput | string
  founded_year?: Prisma.IntFieldUpdateOperationsInput | number
  colors?: Prisma.ClubsUpdatecolorsInput | string[]
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  id?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type ClubsCountOutputType
 */

export type ClubsCountOutputType = {
  Players: number
}

export type ClubsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Players?: boolean | ClubsCountOutputTypeCountPlayersArgs
}

/**
 * ClubsCountOutputType without action
 */
export type ClubsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClubsCountOutputType
   */
  select?: Prisma.ClubsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ClubsCountOutputType without action
 */
export type ClubsCountOutputTypeCountPlayersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlayersWhereInput
}


export type ClubsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  city?: boolean
  country?: boolean
  league?: boolean
  founded_year?: boolean
  colors?: boolean
  deleted_at?: boolean
  id?: boolean
  Players?: boolean | Prisma.Clubs$PlayersArgs<ExtArgs>
  _count?: boolean | Prisma.ClubsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clubs"]>

export type ClubsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  city?: boolean
  country?: boolean
  league?: boolean
  founded_year?: boolean
  colors?: boolean
  deleted_at?: boolean
  id?: boolean
}, ExtArgs["result"]["clubs"]>

export type ClubsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  city?: boolean
  country?: boolean
  league?: boolean
  founded_year?: boolean
  colors?: boolean
  deleted_at?: boolean
  id?: boolean
}, ExtArgs["result"]["clubs"]>

export type ClubsSelectScalar = {
  name?: boolean
  city?: boolean
  country?: boolean
  league?: boolean
  founded_year?: boolean
  colors?: boolean
  deleted_at?: boolean
  id?: boolean
}

export type ClubsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "city" | "country" | "league" | "founded_year" | "colors" | "deleted_at" | "id", ExtArgs["result"]["clubs"]>
export type ClubsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Players?: boolean | Prisma.Clubs$PlayersArgs<ExtArgs>
  _count?: boolean | Prisma.ClubsCountOutputTypeDefaultArgs<ExtArgs>
}
export type ClubsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ClubsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ClubsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Clubs"
  objects: {
    Players: Prisma.$PlayersPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    name: string
    city: string
    country: string
    league: string
    founded_year: number
    colors: string[]
    deleted_at: Date | null
    id: number
  }, ExtArgs["result"]["clubs"]>
  composites: {}
}

export type ClubsGetPayload<S extends boolean | null | undefined | ClubsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClubsPayload, S>

export type ClubsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClubsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClubsCountAggregateInputType | true
  }

export interface ClubsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Clubs'], meta: { name: 'Clubs' } }
  /**
   * Find zero or one Clubs that matches the filter.
   * @param {ClubsFindUniqueArgs} args - Arguments to find a Clubs
   * @example
   * // Get one Clubs
   * const clubs = await prisma.clubs.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClubsFindUniqueArgs>(args: Prisma.SelectSubset<T, ClubsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClubsClient<runtime.Types.Result.GetResult<Prisma.$ClubsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Clubs that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClubsFindUniqueOrThrowArgs} args - Arguments to find a Clubs
   * @example
   * // Get one Clubs
   * const clubs = await prisma.clubs.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClubsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClubsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClubsClient<runtime.Types.Result.GetResult<Prisma.$ClubsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Clubs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubsFindFirstArgs} args - Arguments to find a Clubs
   * @example
   * // Get one Clubs
   * const clubs = await prisma.clubs.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClubsFindFirstArgs>(args?: Prisma.SelectSubset<T, ClubsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClubsClient<runtime.Types.Result.GetResult<Prisma.$ClubsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Clubs that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubsFindFirstOrThrowArgs} args - Arguments to find a Clubs
   * @example
   * // Get one Clubs
   * const clubs = await prisma.clubs.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClubsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClubsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClubsClient<runtime.Types.Result.GetResult<Prisma.$ClubsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Clubs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Clubs
   * const clubs = await prisma.clubs.findMany()
   * 
   * // Get first 10 Clubs
   * const clubs = await prisma.clubs.findMany({ take: 10 })
   * 
   * // Only select the `name`
   * const clubsWithNameOnly = await prisma.clubs.findMany({ select: { name: true } })
   * 
   */
  findMany<T extends ClubsFindManyArgs>(args?: Prisma.SelectSubset<T, ClubsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClubsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Clubs.
   * @param {ClubsCreateArgs} args - Arguments to create a Clubs.
   * @example
   * // Create one Clubs
   * const Clubs = await prisma.clubs.create({
   *   data: {
   *     // ... data to create a Clubs
   *   }
   * })
   * 
   */
  create<T extends ClubsCreateArgs>(args: Prisma.SelectSubset<T, ClubsCreateArgs<ExtArgs>>): Prisma.Prisma__ClubsClient<runtime.Types.Result.GetResult<Prisma.$ClubsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Clubs.
   * @param {ClubsCreateManyArgs} args - Arguments to create many Clubs.
   * @example
   * // Create many Clubs
   * const clubs = await prisma.clubs.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClubsCreateManyArgs>(args?: Prisma.SelectSubset<T, ClubsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Clubs and returns the data saved in the database.
   * @param {ClubsCreateManyAndReturnArgs} args - Arguments to create many Clubs.
   * @example
   * // Create many Clubs
   * const clubs = await prisma.clubs.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Clubs and only return the `name`
   * const clubsWithNameOnly = await prisma.clubs.createManyAndReturn({
   *   select: { name: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ClubsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ClubsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClubsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Clubs.
   * @param {ClubsDeleteArgs} args - Arguments to delete one Clubs.
   * @example
   * // Delete one Clubs
   * const Clubs = await prisma.clubs.delete({
   *   where: {
   *     // ... filter to delete one Clubs
   *   }
   * })
   * 
   */
  delete<T extends ClubsDeleteArgs>(args: Prisma.SelectSubset<T, ClubsDeleteArgs<ExtArgs>>): Prisma.Prisma__ClubsClient<runtime.Types.Result.GetResult<Prisma.$ClubsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Clubs.
   * @param {ClubsUpdateArgs} args - Arguments to update one Clubs.
   * @example
   * // Update one Clubs
   * const clubs = await prisma.clubs.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClubsUpdateArgs>(args: Prisma.SelectSubset<T, ClubsUpdateArgs<ExtArgs>>): Prisma.Prisma__ClubsClient<runtime.Types.Result.GetResult<Prisma.$ClubsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Clubs.
   * @param {ClubsDeleteManyArgs} args - Arguments to filter Clubs to delete.
   * @example
   * // Delete a few Clubs
   * const { count } = await prisma.clubs.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClubsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClubsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Clubs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Clubs
   * const clubs = await prisma.clubs.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClubsUpdateManyArgs>(args: Prisma.SelectSubset<T, ClubsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Clubs and returns the data updated in the database.
   * @param {ClubsUpdateManyAndReturnArgs} args - Arguments to update many Clubs.
   * @example
   * // Update many Clubs
   * const clubs = await prisma.clubs.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Clubs and only return the `name`
   * const clubsWithNameOnly = await prisma.clubs.updateManyAndReturn({
   *   select: { name: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ClubsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ClubsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClubsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Clubs.
   * @param {ClubsUpsertArgs} args - Arguments to update or create a Clubs.
   * @example
   * // Update or create a Clubs
   * const clubs = await prisma.clubs.upsert({
   *   create: {
   *     // ... data to create a Clubs
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Clubs we want to update
   *   }
   * })
   */
  upsert<T extends ClubsUpsertArgs>(args: Prisma.SelectSubset<T, ClubsUpsertArgs<ExtArgs>>): Prisma.Prisma__ClubsClient<runtime.Types.Result.GetResult<Prisma.$ClubsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Clubs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubsCountArgs} args - Arguments to filter Clubs to count.
   * @example
   * // Count the number of Clubs
   * const count = await prisma.clubs.count({
   *   where: {
   *     // ... the filter for the Clubs we want to count
   *   }
   * })
  **/
  count<T extends ClubsCountArgs>(
    args?: Prisma.Subset<T, ClubsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClubsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Clubs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClubsAggregateArgs>(args: Prisma.Subset<T, ClubsAggregateArgs>): Prisma.PrismaPromise<GetClubsAggregateType<T>>

  /**
   * Group by Clubs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClubsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClubsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClubsGroupByArgs['orderBy'] }
      : { orderBy?: ClubsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClubsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClubsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Clubs model
 */
readonly fields: ClubsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Clubs.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClubsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Players<T extends Prisma.Clubs$PlayersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Clubs$PlayersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlayersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Clubs model
 */
export interface ClubsFieldRefs {
  readonly name: Prisma.FieldRef<"Clubs", 'String'>
  readonly city: Prisma.FieldRef<"Clubs", 'String'>
  readonly country: Prisma.FieldRef<"Clubs", 'String'>
  readonly league: Prisma.FieldRef<"Clubs", 'String'>
  readonly founded_year: Prisma.FieldRef<"Clubs", 'Int'>
  readonly colors: Prisma.FieldRef<"Clubs", 'String[]'>
  readonly deleted_at: Prisma.FieldRef<"Clubs", 'DateTime'>
  readonly id: Prisma.FieldRef<"Clubs", 'Int'>
}
    

// Custom InputTypes
/**
 * Clubs findUnique
 */
export type ClubsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubsInclude<ExtArgs> | null
  /**
   * Filter, which Clubs to fetch.
   */
  where: Prisma.ClubsWhereUniqueInput
}

/**
 * Clubs findUniqueOrThrow
 */
export type ClubsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubsInclude<ExtArgs> | null
  /**
   * Filter, which Clubs to fetch.
   */
  where: Prisma.ClubsWhereUniqueInput
}

/**
 * Clubs findFirst
 */
export type ClubsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubsInclude<ExtArgs> | null
  /**
   * Filter, which Clubs to fetch.
   */
  where?: Prisma.ClubsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clubs to fetch.
   */
  orderBy?: Prisma.ClubsOrderByWithRelationInput | Prisma.ClubsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clubs.
   */
  cursor?: Prisma.ClubsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clubs.
   */
  distinct?: Prisma.ClubsScalarFieldEnum | Prisma.ClubsScalarFieldEnum[]
}

/**
 * Clubs findFirstOrThrow
 */
export type ClubsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubsInclude<ExtArgs> | null
  /**
   * Filter, which Clubs to fetch.
   */
  where?: Prisma.ClubsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clubs to fetch.
   */
  orderBy?: Prisma.ClubsOrderByWithRelationInput | Prisma.ClubsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clubs.
   */
  cursor?: Prisma.ClubsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clubs.
   */
  distinct?: Prisma.ClubsScalarFieldEnum | Prisma.ClubsScalarFieldEnum[]
}

/**
 * Clubs findMany
 */
export type ClubsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubsInclude<ExtArgs> | null
  /**
   * Filter, which Clubs to fetch.
   */
  where?: Prisma.ClubsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clubs to fetch.
   */
  orderBy?: Prisma.ClubsOrderByWithRelationInput | Prisma.ClubsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Clubs.
   */
  cursor?: Prisma.ClubsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clubs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clubs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clubs.
   */
  distinct?: Prisma.ClubsScalarFieldEnum | Prisma.ClubsScalarFieldEnum[]
}

/**
 * Clubs create
 */
export type ClubsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubsInclude<ExtArgs> | null
  /**
   * The data needed to create a Clubs.
   */
  data: Prisma.XOR<Prisma.ClubsCreateInput, Prisma.ClubsUncheckedCreateInput>
}

/**
 * Clubs createMany
 */
export type ClubsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Clubs.
   */
  data: Prisma.ClubsCreateManyInput | Prisma.ClubsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Clubs createManyAndReturn
 */
export type ClubsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * The data used to create many Clubs.
   */
  data: Prisma.ClubsCreateManyInput | Prisma.ClubsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Clubs update
 */
export type ClubsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubsInclude<ExtArgs> | null
  /**
   * The data needed to update a Clubs.
   */
  data: Prisma.XOR<Prisma.ClubsUpdateInput, Prisma.ClubsUncheckedUpdateInput>
  /**
   * Choose, which Clubs to update.
   */
  where: Prisma.ClubsWhereUniqueInput
}

/**
 * Clubs updateMany
 */
export type ClubsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Clubs.
   */
  data: Prisma.XOR<Prisma.ClubsUpdateManyMutationInput, Prisma.ClubsUncheckedUpdateManyInput>
  /**
   * Filter which Clubs to update
   */
  where?: Prisma.ClubsWhereInput
  /**
   * Limit how many Clubs to update.
   */
  limit?: number
}

/**
 * Clubs updateManyAndReturn
 */
export type ClubsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * The data used to update Clubs.
   */
  data: Prisma.XOR<Prisma.ClubsUpdateManyMutationInput, Prisma.ClubsUncheckedUpdateManyInput>
  /**
   * Filter which Clubs to update
   */
  where?: Prisma.ClubsWhereInput
  /**
   * Limit how many Clubs to update.
   */
  limit?: number
}

/**
 * Clubs upsert
 */
export type ClubsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubsInclude<ExtArgs> | null
  /**
   * The filter to search for the Clubs to update in case it exists.
   */
  where: Prisma.ClubsWhereUniqueInput
  /**
   * In case the Clubs found by the `where` argument doesn't exist, create a new Clubs with this data.
   */
  create: Prisma.XOR<Prisma.ClubsCreateInput, Prisma.ClubsUncheckedCreateInput>
  /**
   * In case the Clubs was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClubsUpdateInput, Prisma.ClubsUncheckedUpdateInput>
}

/**
 * Clubs delete
 */
export type ClubsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubsInclude<ExtArgs> | null
  /**
   * Filter which Clubs to delete.
   */
  where: Prisma.ClubsWhereUniqueInput
}

/**
 * Clubs deleteMany
 */
export type ClubsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Clubs to delete
   */
  where?: Prisma.ClubsWhereInput
  /**
   * Limit how many Clubs to delete.
   */
  limit?: number
}

/**
 * Clubs.Players
 */
export type Clubs$PlayersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Players
   */
  select?: Prisma.PlayersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Players
   */
  omit?: Prisma.PlayersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlayersInclude<ExtArgs> | null
  where?: Prisma.PlayersWhereInput
  orderBy?: Prisma.PlayersOrderByWithRelationInput | Prisma.PlayersOrderByWithRelationInput[]
  cursor?: Prisma.PlayersWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PlayersScalarFieldEnum | Prisma.PlayersScalarFieldEnum[]
}

/**
 * Clubs without action
 */
export type ClubsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clubs
   */
  select?: Prisma.ClubsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clubs
   */
  omit?: Prisma.ClubsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClubsInclude<ExtArgs> | null
}
